### ISSUE TITLE
[BUG] Images in book cards have no fixed height, causing misalignment

### ISSUE THREAD

**Issue by tvanantwerp** [thisdot/framework.dev#178]
**Describe the bug**
Book thumbnails can be radically different heights, creating unaligned layouts.

**To Reproduce**
1. Add a book image with a large resolution.
2. See how it expands the image area compared to other, smaller images.

**Expected behavior**
Book thumbnails should be displayed with uniform height to create alignment across cards horizontally.

**Screenshots**
![image](https://user-images.githubusercontent.com/2487968/160182531-990414f8-8fa0-4c1a-a076-1cb5a471b987.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Firefox
 - Version: 98.0.2

**Additional context**
Noticed while reviewing #176.

**Comment by iaremarkus** [comment]
Happy to handle this in `resourceCardImageStyle`.

@tvanantwerp do you want to set a `maxHeight` like `180px` so that its _completely_ uniform, or something like `250px` so there is _some_ variation, but within reason?

`250px` 👇
<img width="693" alt="CleanShot 2022-04-13 at 13 15 01" src="https://user-images.githubusercontent.com/936966/163168665-493a0d66-ccc5-4c4d-84c6-348fd44d628f.png">

`180px` 👇
<img width="677" alt="CleanShot 2022-04-13 at 13 15 53" src="https://user-images.githubusercontent.com/936966/163168757-f30c15bd-b21b-4c37-acce-a87992050200.png">

**Comment by iaremarkus** [comment]
nice reasoning @dustinsgoodman thank you. I'll get a PR in shortly 🙏
