### ISSUE TITLE
Check the framework.dev site before releasing it

### ISSUE THREAD

**Issue by Zelig880** [thisdot/framework.dev#356]
Before we can deploy the site to production, we should make sure that our site is fully ready and has no bad links or missing resources.

Please do the following (and anything else that you think it is fair to check):

check all the links
Check all the sidebar links and navigation to make sure resources are correctly linked (correct type)
Check all the images and wordings (heading subheading) on the homepage
Update the social media image, the title, the description, the colour scheme and anything else shown in the following links from the designer (of course just Qwik).
[Hero Graphic](https://www.figma.com/file/kbSN3VYmIzdjQEx5mbBTSs/Framework-Dev?node-id=2731%3A128595)
[Open graph image](https://www.figma.com/file/kbSN3VYmIzdjQEx5mbBTSs/Framework-Dev?node-id=2725%3A130781)
[Loom tutorial](https://www.loom.com/share/8d703c1eb2e548af96ceb6f09d028485)
[Logos](https://www.figma.com/file/kbSN3VYmIzdjQEx5mbBTSs/Framework-Dev?node-id=2732%3A129089)
[Color seeds to build a theme](https://www.figma.com/file/3cAQKdlEpCrz7dgeKzJEqQ/Framework-library?node-id=9276%3A22559)

**Comment by kahlie-huff** [comment]
@dustinsgoodman @robocel it sounds like this one is blocked until we can add the content for the blog and podcasts #298 & #302. Let us know If we need to bring those in to get this one moving. Thank you!

**Comment by dustinsgoodman** [comment]
@kahlie-huff @ihardz #298 & #302 aren't the blockers to releasing this site. The issue is when you go to the website, there's a big broken image and the site logo is missing:
![image](https://user-images.githubusercontent.com/1815379/199292143-a2273cb1-7366-489d-b0cb-9c6d353caa4f.png)

Regarding those 2 tickets though, are they blocked/not done because of a lack of content or they just haven't been started? If not started, let's go ahead and do that. If they're blocked because of an issue of content, let's just add the Modern Web Podcast to podcasts and https://svelte.dev/blog & the This Dot blog to the blog list and move on.
