### ISSUE TITLE
[graphql-pod] Add the correct logo and highlight colors

### ISSUE THREAD

**Issue by WillHutt** [thisdot/framework.dev#432]
In the GraphQL color palette inside `packages>system>src>themes>graphql-color-scheme.ts` add the correct highlight and logo colors. 

For now we currently have placeholder values from #414.

**Comment by WillHutt** [comment]
Updated info from Morgan:


![Image](https://user-images.githubusercontent.com/20880360/200907459-6f9ca9c1-3391-484a-b44b-c33158c3b228.png)

**Comment by morgnism** [comment]
For clarity, "tweak the logo" refers to updating the colour's tonal value for the boundary box containing the logo.

For example, see how Angular uses the same red, but Qwik uses a variation because the logo isn't exact. In Graphql's case, using their logo's pink might work but might also be too bright next to the rest.
![image](https://user-images.githubusercontent.com/9042219/200934404-99c628d4-da12-4c6b-8379-466fb3540ffe.png)

**Comment by jdwilkin4** [comment]
This [ticket](https://github.com/thisdot/framework.dev/issues/415) here is responsible for adding the GraphQL card on the main landing page. 
We can test out the landing page hero and framework footer sections colors at that time.
