### ISSUE TITLE
[deno] 2. Add social image and description

### ISSUE THREAD

**Issue by robocel** [thisdot/framework.dev#492]
# Add framework social image and description

## Background

As an user I would like to have the possibility to share the site on social media and for it to have a nice image and description defined, so that it will increase its visibility and shareability

## Acceptance

- [x] Add metadata description
- [x] Add social image
- [ ] Test the site on "https://socialsharepreview.com/"

**Comment by tyrelchambers** [comment]
this looks to be related to each individual resource like in books for example rather than a general tag we can set somewhere.

**Comment by tyrelchambers** [comment]
requested access to edit figma

**Comment by tyrelchambers** [comment]
Rob and Tom have access now. We just need to finish the OG image by swapping out the qwik logo for the deno logo.

**Comment by tyrelchambers** [comment]
The tests will be easiest to execute when we get some preview deploys for our branch merging to main.

**Comment by tyrelchambers** [comment]
I've tested it on the social preview website and it fails to find the image which makes sense because it's looking for the image on `deno.framework.dev` which doesn't exist yet. If I take our Netlify url and try to access the image with the proper filename, I see the image. Social preview should work fine once the Deno branch is in main and can be found on the root domain.
