### ISSUE TITLE
Update Netlify to only build sites related to content changes

### ISSUE THREAD

**Issue by Atrophius** [thisdot/framework.dev#504]
Right now, the previous on Netlify builds all the framework sites for any changes. We want to update the build process to only build sites that are related to the changes.

There should be a way to do this using the ignore command: https://docs.netlify.com/configure-builds/ignore-builds/

**Comment by lindakatcodes** [comment]
Have an attempt at fixing this in this draft PR: https://github.com/thisdot/framework.dev/pull/516

Each site in Netlify has an environment variable called PUBLIC_SITE_NAME, and the `build-ignore` file in the root of the repo checks against that variable to see which site it's testing. The script and builds are successfully finding the right value and running the check to see if changes have been made to cause the site to be built.

However, the current commands that are running are always exiting with 0, which causes the build to fail. I attempted to make a change to the landing page, which should cause all the other builds to stop but the landing page one to work, and it still failed to build. So something with the current command isn't working right.

The command is based on the Netlify docs that recommend how to check the commits and specific folders to see if they need to build. But clearly something still needs to be adjusted here to actually detect the changes properly. You can find what I'm attempting at the link posted in the description, under the "Mimic default behavior" section.

**Comment by lindakatcodes** [comment]
This should be fixed and working in the updated PR now! 

The way I had this set up initially, it wasn't actually running the `git diff` command - it was just returning the string of the command. That's why it was always failling. The script is updated now to actually execute the `diff` command and if there's data, return an exit code of 1, otherwise an exit code of 0 (which is what Netlify says it needs). Seems to work as expected now!
