### ISSUE TITLE
[BUG] Main deployment is failing.

### ISSUE THREAD

**Issue by Zelig880** [thisdot/framework.dev#778]
This issue was raised by one of our contributor. His PR was worked on and merged, but the deployment did not take place.

https://github.com/thisdot/framework.dev/pull/774

Can someone investigate:
- If the build is actually working correctly after merge
- If there is any other framework site that needs updating
- Find out what the issue is and raise it to the PM

**Comment by dustinsgoodman** [comment]
I just handled this. There was a set of Netlify settings that needed to be corrected. The issue is outside collaborators need to be approved. It's a security concern when secrets are involved and we do have secrets involved. The challenge is ALL framework.dev sites get impacted so when reviewing, folks need to look to see if a message like this one exists:
![image](https://github.com/thisdot/framework.dev/assets/1815379/ad3b9239-aa40-4cd0-ac8d-6734de3317e2)


If it does, action is required BEFORE merging.
